LAMBDA_INIT: 1.0
LAMBDA_LR: 0.001
LAMBDA_MAX: 10.0
ADV_CLIP_ABS: 100.0
NORMALIZE_LAGRANGIAN_ADV: false
WARMUP_ROLLOUTS: 0
ACTOR_LR: 0.0005
CRITIC_LR: 0.00025
NUM_ENVS: 200
NUM_STEPS: 256
TOTAL_TIMESTEPS: 3e7
FC_DIM_SIZE: 64
GRU_HIDDEN_DIM: 256
UPDATE_EPOCHS: 10
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.3
SCALE_CLIP_EPS: false
ENT_COEF: 0.015
ANNEAL_ENT: false
ENT_COEF_END: 0.001
VF_COEF: 0.5
MAX_GRAD_NORM: 0.6
ENV_NAME: MPE_simple_tag_scripted_prey_6v2
SEED: 0
"ENV_KWARGS": {
  "max_steps": 256,
  "score_function": "min",
  "reward_mode": "dense",
  "dense_reward_scale": 1.0,
}

TDD_LATENT_DIM: 64
TDD_OUTPUT_DIM: 32
TDD_LR: 0.01
TDD_DISCOUNT: 0.99
TDD_BATCH_SIZE: 512
TDD_UPDATE_EPOCHS: 25
TDD_USE_DEEP_NETWORK: true
TDD_NUM_RESIDUAL_BLOCKS: 10
INTRINSIC_REWARD_SCALE: 2.0
V_INT_LR: 0.003
V_INT_COEF: 1.0
SD_THRESHOLD_MODE: percentile
SD_THRESHOLD: 0.05
SD_PERCENTILE: 30.0
SD_ADAPTIVE_PERCENTILE: 0.3
SD_THRESHOLD_MIN: 0.05
SD_THRESHOLD_MAX: 10.0
SD_SCALE: 5.0
USE_EXPONENTIAL_SD: true
SD_CLIP_MAX: 10.0
USE_INTER_AGENT_SD: false
INCLUDE_SELF_IN_INTER_SD: false
INTER_SD_WEIGHT: 0.0
WANDB_MODE: disabled
NUM_INTERMEDIATE_VIDEOS: 0
SD_HEATMAP_GRID_RES: 50
GENERATE_PER_AGENT_VIDEOS: false
SPARSE_REWARD: false
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
