ACTOR_LR: 0.0005
CRITIC_LR: 0.00025
NUM_ENVS: 200
NUM_STEPS: 256
TOTAL_TIMESTEPS: 3e7
FC_DIM_SIZE: 64
GRU_HIDDEN_DIM: 256
UPDATE_EPOCHS: 10
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.3
SCALE_CLIP_EPS: false
ENT_COEF: 0.015
ANNEAL_ENT: false
ENT_COEF_END: 0.001
MAX_GRAD_NORM: 0.6
ENV_NAME: MPE_simple_tag_scripted_prey_6v2
SEED: 0
"ENV_KWARGS": {
  "max_steps": 256,
  "score_function": "min",
  "reward_mode": "dense",
  "dense_reward_scale": 1.0,
}

NOISE_DIM: 8
MI_LOSS_WEIGHT: 1.0
DISCRIM_HIDDEN_DIM: 128
DISCRIM_LR: 0.001
HIER_LR: 0.001
HIER_HIDDEN_DIM: 64

WANDB_MODE: disabled
NUM_INTERMEDIATE_VIDEOS: 0
SD_HEATMAP_GRID_RES: 50
GENERATE_PER_AGENT_VIDEOS: false
SPARSE_REWARD: false
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
