RCB_BETA_MAX: 0.5
RCB_KAPPA: 0.01
RCB_TARGET: 400.0
RCB_EMA_ALPHA: 0.03
RCB_BETA_MIN: 0.1

RSQ_LAMBDA: 3.0
RSQ_REF: 0.5
RSQ_H_MIN: 0.1
RSQ_H_MAX: 2.0
RSQ_EMA_ALPHA: 0.1

INTRINSIC_REWARD_BETA: 0.5
ACTOR_LR: 0.001
CRITIC_LR: 0.0005
NUM_ENVS: 200
NUM_STEPS: 256
TOTAL_TIMESTEPS: 3e7
FC_DIM_SIZE: 64
GRU_HIDDEN_DIM: 256
UPDATE_EPOCHS: 10
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.3
SCALE_CLIP_EPS: false
ENT_COEF: 0.015
ANNEAL_ENT: false
ENT_COEF_END: 0.001
MAX_GRAD_NORM: 0.6
WARMUP_ROLLOUTS: 0
ENV_NAME: MPE_simple_corridor_v3
SEED: 84
"ENV_KWARGS": {
  "num_agents": 8,
  "action_type": "Discrete",
  "max_steps": 256,
  "local_ratio": 0.5,
}

TDD_LATENT_DIM: 64
TDD_OUTPUT_DIM: 32
TDD_LR: 0.01
TDD_DISCOUNT: 0.99
TDD_BATCH_SIZE: 512
TDD_UPDATE_EPOCHS: 25
TDD_USE_DEEP_NETWORK: true
TDD_NUM_RESIDUAL_BLOCKS: 10
INTRINSIC_REWARD_SCALE: 2.0
WANDB_MODE: disabled
NUM_INTERMEDIATE_VIDEOS: 0
SD_HEATMAP_GRID_RES: 50
GENERATE_PER_AGENT_VIDEOS: false
SPARSE_REWARD: false
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
