RCB_BETA_MAX: 0.5
RCB_KAPPA: 0.01
RCB_TARGET: 3.0
RCB_EMA_ALPHA: 0.03
RCB_BETA_MIN: 0.3

RSQ_LAMBDA: 5.0
RSQ_REF: 0.5
RSQ_H_MIN: 0.1
RSQ_H_MAX: 2.0
RSQ_EMA_ALPHA: 0.1

INTRINSIC_REWARD_BETA: 0.5
ACTOR_LR: 0.0005
CRITIC_LR: 0.0005
NUM_ENVS: 128
NUM_STEPS: 128
TOTAL_TIMESTEPS: 2e7
FC_DIM_SIZE: 64
GRU_HIDDEN_DIM: 128
UPDATE_EPOCHS: 8
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
SCALE_CLIP_EPS: false
ENT_COEF: 0.01
ANNEAL_ENT: false
ENT_COEF_END: 0.001
MAX_GRAD_NORM: 10.0
WARMUP_ROLLOUTS: 20
ENV_NAME: SMAX_27m_vs_30m
SEED: 0
"ENV_KWARGS": {}

SD_INPUT_DIM: 4
SD_POS_START: 728
SD_POS_END: 732

TDD_LATENT_DIM: 64
TDD_OUTPUT_DIM: 32
TDD_LR: 0.01
TDD_DISCOUNT: 0.99
TDD_BATCH_SIZE: 512
TDD_UPDATE_EPOCHS: 25
TDD_USE_DEEP_NETWORK: true
TDD_NUM_RESIDUAL_BLOCKS: 10
INTRINSIC_REWARD_SCALE: 0.01
WANDB_MODE: disabled

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
